var nombre1 = prompt ("Ingrese nombre del inversor 1: ")
var capital1 = parseInt(prompt ("Ingrese capital invertido del inversor 1: "))
var nombre2 = prompt ("Ingrese nombre del inversor 2: ")
var capital2 = parseInt(prompt ("Ingrese capital invertido del inversor 2: "))
var nombre3 = prompt ("Ingrese nombre del inversor 3: ")
var capital3 = parseInt(prompt ("Ingrese capital invertido del inversor 3: "))
var montoTotal = capital1 + capital2 + capital3
var inversion1 = parseInt((capital1 * 100)/montoTotal)
var inversion2 = parseInt((capital2 * 100)/montoTotal)
var inversion3 = parseInt((capital3 * 100)/montoTotal)
console.log("El capital total es de $ " + montoTotal)
console.log(nombre1 + " aportó el " + inversion1 + " % del capital total.")
console.log(nombre2 + " aportó el " + inversion2 + " % del capital total.")
console.log(nombre3 + " aportó el " + inversion3 + " % del capital total.")